#!/usr/bin/env python3
"""Build PARTS.md — the stockroom pick list, from layout.json.

Quantities and reference designators are derived, so the list cannot drift from
the placement the way a hand-written one would. What cannot be derived is
judgement: how many spares to carry, and whether a value may be substituted from
whatever is actually in the drawer. That lives in ADVICE below, and the script
**refuses to write** if a part in layout.json has no entry — so adding a part to
the build forces a decision about it rather than silently dropping it.

    python layout.py      # writes layout.json (refuses if the netlist check fails)
    python gen_parts.py   # then this
"""
import collections
import json
import pathlib
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

HERE = pathlib.Path(__file__).parent
D = json.loads((HERE / "layout.json").read_text(encoding="utf-8"))

# How each kind is described on a stockroom counter, and the order to walk the
# drawers in.
KINDS = [
    ("res",   "Resistors — ¼ W"),
    ("cer",   "Capacitors — ceramic"),
    ("film",  "Capacitors — film"),
    ("elec",  "Capacitors — electrolytic"),
    ("diode", "Diodes"),
    ("bead",  "Ferrite beads"),
    ("dip8",  "Integrated circuits"),
]
HEADER_KINDS = ("hdr2", "hdr5", "hdr6", "hdr10")

# (kind, value) -> (take, substitute note, critical)
# `take` includes spares: these are free at a stockroom and breadboard leads bend.
# `critical` marks the ones that set a gain, a corner frequency or a termination,
# where taking "something close" changes the circuit.
ADVICE = {
    ("res", "10"):     (2,  "10–22 Ω fine", False),
    ("res", "33"):     (5,  "22–68 Ω fine", False),
    ("res", "47"):     (2,  "47–100 Ω fine", False),
    ("res", "49.9"):   (2,  "**want 1 %** — this is the mixer IF termination. "
                            "47 Ω 5 % works if that is all there is", True),
    ("res", "100"):    (2,  "68–150 Ω fine", False),
    ("res", "1k"):     (6,  "**no** — sets amplifier gain with the 100 k", True),
    ("res", "10k"):    (14, "**no** — gain, bias, and the half-rail divider. "
                            "R9 and R10 want to match each other", True),
    ("res", "100k"):   (3,  "**no** — sets gain with the 1 k", True),
    ("cer", "1n"):     (2,  "any; C0G nicest", False),
    ("cer", "10n"):    (2,  "**value matters** — sets the 15.9 kHz anti-alias "
                            "corner with R12. C0G or film", True),
    ("cer", "100n"):   (8,  "any; all of these are decoupling", False),
    ("film", "100n"):  (3,  "**must be film, not ceramic** — signal path", True),
    ("elec", "10u"):   (7,  "any ≥ 16 V", False),
    ("elec", "47u"):   (2,  "any ≥ 16 V", False),
    ("elec", "100u"):  (4,  "**≥ 25 V** — two of these sit on the 12 V rail", True),
    ("diode", "1N5822"): (2, "any 1–3 A Schottky, ≥ 30 V", False),
    ("bead", "FB"):    (4,  "any through-hole ferrite bead", False),
    ("dip8", "TL072CP"): (3, "**DIP-8 package.** TL072, TL072C or TL082 all fit", True),
}

# Values the build sheet does not carry but the bench needs anyway.
EXTRA = [
    ("4.7 k resistor", 2, "R4 takes 4.7 k for gain 22 on first power-up, then 1 k for full gain"),
    ("0.1″ male header strip, 40-pin", 2, "snap to length"),
    ("830-point breadboard", 1, ""),
]


def main():
    parts = D["parts"]
    wires = D["wires"]

    groups = collections.defaultdict(lambda: collections.defaultdict(list))
    for p in parts:
        groups[p["kind"]][p["value"]].append(p["ref"])

    missing = [(k, v) for k, vals in groups.items() if k not in HEADER_KINDS
               for v in vals if (k, v) not in ADVICE]
    if missing:
        print("gen_parts: no ADVICE entry for %s" % sorted(missing), file=sys.stderr)
        print("Add one (take, substitute note, critical) and re-run.", file=sys.stderr)
        return 1

    out = []
    w = out.append
    w("# Stockroom pick list\n")
    w("Generated by `gen_parts.py` from `layout.json` — the same placement "
      "`WIRING.md` and `ASSEMBLY.md` come from, so the counts cannot drift from "
      "the build. Re-run it after `layout.py`.\n")
    w("**Take** includes spares. Passives are free or nearly free at a university "
      "stockroom and breadboard leads bend, so carry a few extra of everything "
      "cheap. The substitute column is what to do if the drawer is empty.\n")

    placed = 0
    for kind, title in KINDS:
        if kind not in groups:
            continue
        w("## %s\n" % title)
        w("| value | need | take | substitute? | refs |")
        w("|---|---|---|---|---|")
        rows = sorted(groups[kind].items(), key=lambda kv: (-len(kv[1]), kv[0]))
        for value, refs in rows:
            take, sub, crit = ADVICE[(kind, value)]
            placed += len(refs)
            name = "**%s**" % value if crit else value
            w("| %s | %d | %d | %s | %s |" % (name, len(refs), take, sub, ", ".join(refs)))
        w("")

    hdr = collections.Counter()
    hpins = 0
    for p in parts:
        if p["kind"] in HEADER_KINDS:
            n = int(p["kind"][3:])
            hdr[n] += 1
            hpins += n
            placed += 1
    w("## Headers\n")
    w("| strip | qty | on |")
    w("|---|---|---|")
    for n in sorted(hdr):
        refs = [p["ref"] for p in parts if p["kind"] == "hdr%d" % n]
        w("| %d-pin | %d | %s |" % (n, hdr[n], ", ".join(refs)))
    w("")
    w("%d header pins in %d strips. Cut them from a 40-pin strip.\n"
      % (hpins, sum(hdr.values())))

    w("## Also on the list\n")
    w("| item | take | note |")
    w("|---|---|---|")
    for item, qty, note in EXTRA:
        w("| %s | %d | %s |" % (item, qty, note))
    w("")

    cols = collections.Counter(x["colour"] for x in wires)
    w("## Jumper wire\n")
    w("Solid-core 22 AWG, %d links in total:\n" % len(wires))
    w("| colour | links |")
    w("|---|---|")
    for c, n in cols.most_common():
        w("| %s | %d |" % (c, n))
    w("")

    w("## What not to compromise on\n")
    w("Everything marked **bold** above sets a gain, a corner frequency or a "
      "termination. Taking \"something close\" there changes the circuit rather "
      "than the parts list:\n")
    w("- the two **film** 100 nF are the high-passes in a 61 dB amplifier; "
      "ceramics there are microphonic and have a voltage coefficient")
    w("- the **1 k / 10 k / 100 k** set the gain and the half-rail reference — "
      "if the stockroom has 1 %, take those")
    w("- the **49.9 Ω** is the mixer's IF load; without it conversion loss and "
      "flatness wander")
    w("- a **DIP** TL072: stockrooms usually have them loose, distributors "
      "increasingly do not\n")
    w("And the thing actually worth borrowing while you are in the building is a "
      "**VNA that reaches 2.5 GHz** — a ~$165 instrument you need for twenty "
      "minutes, against which this whole list is rounding error. "
      "`docs/radar-hardware.md` covers what to measure with it.\n")

    (HERE / "PARTS.md").write_text("\n".join(out), encoding="utf-8")
    print("PARTS.md: %d placed components (%d distinct lines), %d jumpers"
          % (placed, sum(len(v) for v in groups.values()), len(wires)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
